
# Replace the text below to customize your site
site_name: Oliver - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Oliver Lloyd
copyright: Copyright 2023 "Oliver Lloyd" - GNU Free Documentation License
repo_name: 'Oliver-MDEF-Portfolio : Github Repo'
site_url: https://oliver-lloyd-mdef.github.io/Oliver-MDEF-Portfolio/
repo_url: https://github.com/Oliver-Lloyd-MDEF/Oliver-MDEF-Portfolio


nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
      - Bootcamp: term1/01-Bootcamp.md
      - Documenting Design: term1/07-Documenting Design.md
      - Design Studio 01 - Roles of prototyping: term1/02-Design Studio 01 - Roles of Prototyping in First Person Person Perspectives.md
      - Design Studio 01.01 - Our first intervention: term1/06-Design Studio 02 - Our first Intervention.md
      - Design Studio 01.02 - Roles of Personal & Collective Storytelling: term1/08-Design Studio 01.03 - Narratives & Storytelling.md
      - Atlas of Weak Signals: term1/03-Atlas of Weak Signals.md
      - The Machine Paradox: term1/04-The Machine Paradox.md
      - Living with your own ideas: term1/05-Living with your own ideas.md
      - Bio Zero: term1/09-Bio Zero.md
      - Agri Zero: term1/10-Agri Zero.md
    
      
  #- Term 2:
   #   - digi: Term 2/digi.md
   #   - studio: Term 2/studio.md
  #- End of Week Reflections:
      #- Week 1 - A soft landing: End of week reflections/Week 1 - A soft landing.md
      #- Week 2 - Searching for Signals: End of week reflections/Week 2 - Searching for Signals.md
  #- Master project:
  #    - Initial ideas: project/project.md
  - Coding Support: Coding Support.md
  - Test Index: test index.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    #- icon: fontawesome/brands/web
    #  link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/oliver_lloyd_design/
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/oliverlloyddesign/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: Oliver Lloyd Design
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: custom
    accent: custom
  extra_css:
    - stylesheets/extra.css
    - custom.css

  # Light mode
  toggle:
    name: Switch to Dark Mode
    icon: material/brightness-7
    primary: Oliver Lloyd Design

  # Dark mode
  toggle:
    name: Switch to Light Mode
    icon: material/brightness-4
    scheme: slate


  toggle:
    - icon: material/brightness-7
      name: Switch to dark mode
    - icon: material/brightness-4
      name: Switch to light mode



  font:
    # See available fonts at https://fonts.google.com/
    text: Space Grotesk
    code: Space Mono
  
  logo: images/Logos/circle_logo_white.png
  favicon: images/Logos/Circular Olive Branch logo.png
  features:
    - instant
    - header.autohide
    - navigation.expand
    - #navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate

plugins:
   - search
   - git-revision-date-localized:
       fallback_to_build_date: true



markdown_extensions:
  - attr_list
  - md_in_html
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.escapeall:
        hardbreak: true

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css

use_directory_urls: false

