name: Deploy to Github Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'   
        
    - uses: actions/checkout@v4 # Updated to v4
      
    - name: Setup Python
      uses: actions/setup-python@v5 # Updated to v5
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: mkdocs build
      run: |
        pip freeze
        pip --version
        python --version
        mkdocs --version
        mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
